// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function FetchConfig() {
  return window['go']['main']['App']['FetchConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetServiceUptime() {
  return window['go']['main']['App']['GetServiceUptime']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoadLocalConfig() {
  return window['go']['main']['App']['LoadLocalConfig']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}
