// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {service} from '../models';
import {storage} from '../models';
import {auth} from '../models';

export function ClearLogs():Promise<void>;

export function FetchConfig():Promise<config.FrpConfig>;

export function GetLogs(arg1:number):Promise<Array<service.LogEntry>>;

export function GetProxies():Promise<Array<service.ProxyStatus>>;

export function GetServiceStatus():Promise<string>;

export function GetServiceUptime():Promise<string>;

export function GetSettings():Promise<storage.Settings>;

export function GetUserInfo():Promise<auth.UserInfo>;

export function IsLoggedIn():Promise<boolean>;

export function LoadLocalConfig():Promise<config.FrpConfig>;

export function Login(arg1:string):Promise<boolean>;

export function Logout():Promise<void>;

export function RestartService():Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;
